<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">

<script type="text/javascript" src="../sh_main.js"></script>
<script type="text/javascript" src="../sh_cpp.js"></script>
<!--[IF IE]>
	<script type="text/javascript" src="ierange.js"></script>
<![ENDIF]-->
<script type="text/javascript" src="../masha.min.js"></script>
<script type="text/javascript" src="../all_pack.js"></script>
<link rel="stylesheet" type="text/css" href="../css/masha.css">
<link rel="stylesheet" type="text/css" href="../sh_print.css">
<link rel="stylesheet" type="text/css" href="../toc.css">
<link rel="stylesheet" type="text/css" href="../styles.css">
<script type="text/javascript" src="../page.js"></script>

<title>The std::uncaught_exception() function</title>
</head>
<body>
<h3>
<dfn class="label">[except.uncaught]</dfn><object type="application/x-oleobject" classid="clsid:1e2a7bd0-dab9-11d0-b93a-00c04fc99f9e"><param name="Keyword" value="[except.uncaught]"></object>15.5.3 The <code class="sh_cpp">std::uncaught_exception()</code> function </h3>

<p><a class="anchor" id="p1" href="#p1">1</a>The function <code class="sh_cpp">std::uncaught_exception()</code> returns <code class="sh_cpp">true</code> after completing the
initialization of the exception object (<a title="except.throw" href="except.throw.html">15.1</a>) until completing the activation of a handler for the exception
(<a title="except.handle" href="except.handle.html">15.3</a>, <a title="uncaught" href="uncaught.html">18.8.4</a>). This includes stack unwinding. If the exception is rethrown (<a title="except.throw" href="except.throw.html">15.1</a>),
<code class="sh_cpp">std::uncaught_exception()</code> returns <code class="sh_cpp">true</code> from the point of rethrow until the rethrown exception
is caught again.</p>
</body>
</html>



